title: Yun Cheng
logo: /assets/img/avatar.png
description:
google_analytics:
theme: jekyll-theme-minimal

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge


# social-network-links:
#   email: "yuncheng@andrew.cmu.edu"
#   facebook: "https://www.facebook.com/yun.cheng.7545"
#   github: "https://github.com/kapikantzari"
#   linkedin: "https://www.linkedin.com/in/yun-catherine-cheng/"
